// RTP calibration: node tools/simulate.js [spins] [--write]
const U = require('../js/util.js');
const E = require('../js/engine.js');
const MACHINES = require('../js/machines.js');
const N = +process.argv[2] || 100000;
const write = process.argv.includes('--write');
const only = process.argv.find((a) => a.startsWith('--only='));
const TARGET = 0.96;
const out = {};
for (const cfg of MACHINES) {
  if (only && cfg.id !== only.slice(7)) continue;
  const m = E.prepare(cfg, null);
  m.scale = 1;
  let win = 0, hits = 0, fs = 0, hw = 0, wh = 0, base = 0, fsWin = 0;
  const t0 = Date.now();
  for (let i = 0; i < N; i++) {
    const s = E.simRound(m, 1);
    win += s.win; base += s.base;
    if (s.base > 0) hits++;
    fs += s.fs; hw += s.hw; wh += s.wheel;
  }
  const rtp = win / N;
  const scale = TARGET / rtp;
  out[cfg.id] = +scale.toFixed(4);
  console.log(cfg.id.padEnd(18), 'rawRTP', rtp.toFixed(3), 'baseShare', (base / win).toFixed(2),
    'hit%', (100 * hits / N).toFixed(1), 'fs 1/' + (fs ? Math.round(N / fs) : '-'),
    'hw 1/' + (hw ? Math.round(N / hw) : '-'), 'wheel 1/' + (wh ? Math.round(N / wh) : '-'),
    'scale', scale.toFixed(3), (Date.now() - t0) + 'ms');
}
if (write) {
  const fs = require('fs');
  fs.writeFileSync(__dirname + '/../js/calibration.js',
    '/* Generated by tools/simulate.js: pay scale per machine for ~96% RTP */\n' +
    '(function (root) { root.SLOT_CALIBRATION = ' + JSON.stringify(out, null, 1) + '; })(typeof window !== "undefined" ? window : globalThis);\n');
}
